Month8/step1
stan99-cheb/react-burger pull request #3
Opened 2022-10-22 07:59 UTC by stan99-cheb

2022-10-22 09:54 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;
- Правильно используйте useReducer;

### **Но есть несколько замечаний, которые нужно исправить:**

- По макету, 1 ссылка в хедере `конструктор` - должна быть активна;

  ![image](https://user-images.githubusercontent.com/70164458/197333114-9da5bd06-8ac0-4098-b286-228bfcc1e80b.png)

- Исправьте ошибку в консоли браузера;

  ![image](https://user-images.githubusercontent.com/70164458/197333119-13e67236-786e-4764-b8be-582f184f4433.png)

- При отправке запроса на получения номера заказа, не забывайте что булки у нас 2, поэтому их id должны быть в начале, и в конце массива. Сейчас у вас id-булки стоит только в начале массива. Также исправьте момент с ценой, там тоже цена булки должна быть умножена на 2.

  ![image](https://user-images.githubusercontent.com/70164458/197333133-6fb7f1f4-a5a3-4451-a1b2-17c48cef4f22.png)

- Перенести папку UI из корня проекта, в `components`;

- Вынести папку utils из папки `components`, в корень проекта;

- Константа `baseUrl` - имена констант принято записывать в стиле UPPER_CASE;

### **Сделает код лучше:**

- При клике на таб скролить список ингредиентов к нужному разделу.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-22 09:54 UTC, ArslanDev666 commented on src/components/BurgerIngredients/burger-ingredients.jsx
>    const mainsIngredient = data.filter((item) => item.type === 'main');
**Можно лучше:** лучше обернуть в useMemo.

2022-10-22 20:01 UTC, stan99-cheb commented on src/components/BurgerIngredients/burger-ingredients.jsx
>    const mainsIngredient = data.filter((item) => item.type === 'main');
У меня ошибок в консоли браузера нет. Я почистил локальный кэш и сделал коммит.

2022-10-23 04:44 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

2022-10-23 08:26 UTC, merged